export const products = [
  {
    model: 'FX-65',
    title: 'Pralnicowirówka wysokoobrotowa, typ FX-65',
    category: 'Pralnicowirówki wysokoobrotowe',
    description:
      'Najlepszy wybór do pralni przemysłowych, których dzialanie wymaga najlepszych z najlepszych rozwiązań pralniczych. Zaprojektowane, aby zapewnić najniższe koszty zużycia wody i energii, wysoką wydajność i przyjazną obsługę. Innowacyjne technologie: CascadeDrum, supereco, Xcontrol FLEX +, czy TRACE-TECH, czynią je bezkonkurencyjne na rynku.',
    line: 'Linia FX',
    available_models: [
      { title: 'FX-65', subtitle: 'załadunek 6.5 - 7 kg' },
      { title: 'FX-80', subtitle: 'załadunek 8 - 9 kg' },
      { title: 'FX-105', subtitle: 'załadunek 10.5 - 12 kg' },
      { title: 'FX-135', subtitle: 'załadunek 13.5 - 15 kg' },
      { title: 'FX-180', subtitle: 'załadunek 18 - 20 kg' },
      { title: 'FX-240', subtitle: 'załadunek 24 - 27 kg' },
      { title: 'FX-280', subtitle: 'załadunek 28 -32 kg' },
    ],
    slider: [
      'fx105_01',
      'fx105_02',
      'fx105_03',
      'fx105_04',
      'fx105_05',
      'fx105_06',
    ],
    isSliderVertical: false,
    features: [
      'wolnostojąca wysokoobrotowa',
      'nierdzewny panel górny',
      'przedni i boczne panele ocynkowane lakierowane w aktrakcyjnym kolorze stali INOX',
      'nierdzewny bęben wewnętrzny i zewnętrzny',
      'XControl - łatwy w użyciu sterownik mikroprocesorowy',
      'opatentowany pojemnik na detergenty',
      'duża średnica zaworu spustowego - 76 mm',
      'łatwy dostęp do wszystkich istotnych podzespołów',
      'szeroko otwierane drzwi dla łatwego załadunku i wyładunku',
      'moduł podłączenia do 8 sygnałów pomp płynnych środków piorących',
      'napęd z przemiennikiem częstotliwości',
    ],
    parameters: [
      { name: 'załadunek (moduł załadunku 1:10)', value: '6.5', unit: 'kg' },
      {
        name: 'załadunek maksymalny (moduł załadunku 1:9)',
        value: '7',
        unit: 'kg',
      },
      { name: 'pojemność bębna', value: '65', unit: 'litrów' },
      { name: 'średnica bębna', value: '530', unit: 'mm' },
      { name: 'obrtoty prania', value: '49', unit: 'obr./min.' },
      { name: 'obrtoty wirowania', value: '1165', unit: 'obr./min.' },
      { name: 'G-faktor', value: '400', unit: '-' },
      { name: 'moc podgrzewu elektrycznego', value: '6/9', unit: 'kW' },
      {
        name: 'podłączenie pary (dla podgrzewu parowego)',
        value: '1/2',
        unit: 'cal',
      },
      {
        name: 'ciśnienie pary (dla podgrzewu parowego)',
        value: '1 - 8',
        unit: 'bar',
      },
      { name: 'podłączenie wody', value: '3/4', unit: 'cal' },
      { name: 'ciśnienie wody', value: '1 - 8', unit: 'bar' },
      {
        name: 'zasilanie (standard)',
        value: '3x380 - 415/50Hz/3',
        unit: '-',
      },
      { name: 'wymiary (w. x sz. x gł.)', value: '1115x710x740', unit: 'mm' },
      { name: 'masa netto', value: '170', unit: 'kg' },
      { name: 'masa brutto', value: '180', unit: 'kg' },
    ],
    controls: [
      {
        name: 'XControl FLEX +',
        image: 'XControl FLEX Plus',
        list: [
          '7 calowy ekran dotykoway',
          'możliwość wyświetlania komunikatów w 34 językach',
          'wbudowane wifi',
          'zdalne programowanie i aktualizacje',
          'w pełni programowalny',
          '20 fabrycznych programów prania spełniających wszystkie podstawowe potrzeby',
          'do 99 programów użytkownika',
        ],
      },
      {
        name: 'XControl +',
        image: 'XControl Plus',
        list: [
          'do 99 programów prania',
          'w pełni programowalny',
          'wyświetlacz graficzny',
          'obsługa w 21 językach, w tym polskim',
          'port USB',
        ],
      },
      {
        name: 'XControl',
        image: 'XControl',
        list: [
          '15 programów prania',
          'w pełni programowalny',
          'wyświetlacz graficzny',
          'obsługa w 25 językach, w tym w polskim',
          'port USB',
        ],
      },
    ],
    leaflets: [
      { label: 'karta informacyjna', fileName: 'FX6580105135 KI' },
      {
        label: 'instrukcja instalacji pralnicowirówki',
        fileName: '',
      },
    ],
  },
  {
    model: 'FX-80',
    title: 'Pralnicowirówka wysokoobrotowa, typ FX-80',
    category: 'Pralnicowirówki wysokoobrotowe',
    description:
      'Najlepszy wybór do pralni przemysłowych, których dzialanie wymaga najlepszych z najlepszych rozwiązań pralniczych. Zaprojektowane, aby zapewnić najniższe koszty zużycia wody i energii, wysoką wydajność i przyjazną obsługę. Innowacyjne technologie: CascadeDrum, supereco, Xcontrol FLEX +, czy TRACE-TECH, czynią je bezkonkurencyjne na rynku.',
    line: 'Linia FX',
    available_models: [
      { title: 'FX-65', subtitle: 'załadunek 6.5 - 7 kg' },
      { title: 'FX-80', subtitle: 'załadunek 8 - 9 kg' },
      { title: 'FX-105', subtitle: 'załadunek 10.5 - 12 kg' },
      { title: 'FX-135', subtitle: 'załadunek 13.5 - 15 kg' },
      { title: 'FX-180', subtitle: 'załadunek 18 - 20 kg' },
      { title: 'FX-240', subtitle: 'załadunek 24 - 27 kg' },
      { title: 'FX-280', subtitle: 'załadunek 28 -32 kg' },
    ],
    slider: [
      'fx105_01',
      'fx105_02',
      'fx105_03',
      'fx105_04',
      'fx105_05',
      'fx105_06',
    ],
    isSliderVertical: false,
    features: [
      'wolnostojąca wysokoobrotowa',
      'nierdzewny panel górny',
      'przedni i boczne panele ocynkowane lakierowane w aktrakcyjnym kolorze stali INOX',
      'nierdzewny bęben wewnętrzny i zewnętrzny',
      'XControl - łatwy w użyciu sterownik mikroprocesorowy',
      'opatentowany pojemnik na detergenty',
      'duża średnica zaworu spustowego - 76 mm',
      'łatwy dostęp do wszystkich istotnych podzespołów',
      'szeroko otwierane drzwi dla łatwego załadunku i wyładunku',
      'moduł podłączenia do 8 sygnałów pomp płynnych środków piorących',
      'napęd z przemiennikiem częstotliwości',
    ],
    parameters: [
      { name: 'załadunek (moduł załadunku 1:10)', value: '7.5', unit: 'kg' },
      {
        name: 'załadunek maksymalny (moduł załadunku 1:9)',
        value: '9',
        unit: 'kg',
      },
      { name: 'pojemność bębna', value: '75', unit: 'litrów' },
      { name: 'średnica bębna', value: '530', unit: 'mm' },
      { name: 'obrtoty prania', value: '49', unit: 'obr./min.' },
      { name: 'obrtoty wirowania', value: '1165', unit: 'obr./min.' },
      { name: 'G-faktor', value: '400', unit: '-' },
      { name: 'moc podgrzewu elektrycznego', value: '6/9', unit: 'kW' },
      {
        name: 'podłączenie pary (dla podgrzewu parowego)',
        value: '1/2',
        unit: 'cal',
      },
      {
        name: 'ciśnienie pary (dla podgrzewu parowego)',
        value: '1 - 8',
        unit: 'bar',
      },
      { name: 'podłączenie wody', value: '3/4', unit: 'cal' },
      { name: 'ciśnienie wody', value: '1 - 8', unit: 'bar' },
      {
        name: 'zasilanie (standard)',
        value: '3x380 - 415/50Hz/3',
        unit: '-',
      },
      { name: 'wymiary (w. x sz. x gł.)', value: '1115x710x790', unit: 'mm' },
      { name: 'masa netto', value: '185', unit: 'kg' },
      { name: 'masa brutto', value: '200', unit: 'kg' },
    ],
    controls: [
      {
        name: 'XControl FLEX +',
        image: 'XControl FLEX Plus',
        list: [
          '7 calowy ekran dotykoway',
          'możliwość wyświetlania komunikatów w 34 językach',
          'wbudowane wifi',
          'zdalne programowanie i aktualizacje',
          'w pełni programowalny',
          '20 fabrycznych programów prania spełniających wszystkie podstawowe potrzeby',
          'do 99 programów użytkownika',
        ],
      },
      {
        name: 'XControl +',
        image: 'XControl Plus',
        list: [
          'do 99 programów prania',
          'w pełni programowalny',
          'wyświetlacz graficzny',
          'obsługa w 21 językach, w tym polskim',
          'port USB',
        ],
      },
      {
        name: 'XControl',
        image: 'XControl',
        list: [
          '15 programów prania',
          'w pełni programowalny',
          'wyświetlacz graficzny',
          'obsługa w 25 językach, w tym w polskim',
          'port USB',
        ],
      },
    ],
    leaflets: [
      { label: 'karta informacyjna', fileName: 'FX6580105135 KI' },
      {
        label: 'instrukcja instalacji pralnicowirówki',
        fileName: 'FX80 instalacja',
      },
    ],
  },
  {
    model: 'FX-350',
    title: 'Wysokowydajna pralnicowirówka wysokoobrotowa, typ FX-350',
    category: 'Pralnicowirówki wysokoobrotowe',
    description:
      'Najlepszy wybór do pralni przemysłowych, których dzialanie wymaga najlepszych z najlepszych rozwiązań pralniczych. Zaprojektowane, aby zapewnić najniższe koszty zużycia wody i energii, wysoką wydajność i przyjazną obsługę. Innowacyjne technologie: CascadeDrum, supereco, Xcontrol FLEX +, TRACE-TECH, system ważenia wsadu Optiload, czy system przechyłu przedniego, czynią je bezkonkurencyjne na rynku.',
    line: 'Linia FX',
    available_models: [
      { title: 'FX-350', subtitle: 'załadunek 35 - 39 kg' },
      { title: 'FX-450', subtitle: 'załadunek 45 - 50 kg' },
      { title: 'FX-600', subtitle: 'załadunek 60 - 67 kg' },
    ],
    slider: [
      'fx350_01',
      'fx350_02',
      'fx350_03',
      'fx350_04',
      'fx350_05',
      'fx350_06',
    ],
    isSliderVertical: false,
    features: [
      'wolnostojąca wysokoobrotowa',
      'bęben wewnętrzny i zewnętrzny ze stali nierdzewnej',
      '2 duże zawory spustowe 2 x 76 mm',
      'łatwy dostęp do wszystkich najważniejszych części od przodu',
      'EasySoap - możliwość podłączenia do 8-śmiu pomp płynnych środków piorących',
      'napęd z przemiennikiem częstotliwości',
      'perforowane przewały - technologia PowerWash',
      'pojemnik na środki piorące z 5-cioma wyjmowanymi komorami',
      'ergonomiczna wysokość drzwi i pozycja sterowania',
      'sterownik mikroprocesorowy Xcontrol Plus w standardzie',
      'port RS485 i USB',
      'sygnał końca cyklu',
      'w opcji system ważenia wsadu, nierdzewny przód, sterownik Xcontrol Flex +, pneumatyczne zawory zasilające, 3 zawór zasilający, system przechyłu przedniego dla FX450 i  FX600',
    ],
    parameters: [
      { name: 'załadunek (moduł załadunku 1:10)', value: '35', unit: 'kg' },
      {
        name: 'załadunek maksymalny (moduł załadunku 1:9)',
        value: '39',
        unit: 'kg',
      },
      { name: 'pojemność bębna', value: '350', unit: 'litrów' },
      { name: 'średnica bębna', value: '914', unit: 'mm' },
      { name: 'obrtoty prania', value: '45', unit: 'obr./min.' },
      { name: 'obrtoty wirowania', value: '839', unit: 'obr./min.' },
      { name: 'G-faktor', value: '360', unit: '-' },
      { name: 'moc podgrzewu elektrycznego', value: '24', unit: 'kW' },
      {
        name: 'podłączenie pary (dla podgrzewu parowego)',
        value: '3/4',
        unit: 'cal',
      },
      {
        name: 'ciśnienie pary (dla podgrzewu parowego)',
        value: '1 - 8',
        unit: 'bar',
      },
      { name: 'podłączenie wody', value: '1', unit: 'cal' },
      { name: 'ciśnienie wody', value: '1 - 8', unit: 'bar' },
      {
        name: 'zasilanie (standard)',
        value: '3x380 - 415/50Hz/3',
        unit: '-',
      },
      { name: 'wymiary (w. x sz. x gł.)', value: '1925x1315x1270', unit: 'mm' },
      { name: 'masa netto', value: '1010', unit: 'kg' },
      { name: 'masa brutto', value: '1170', unit: 'kg' },
    ],
    controls: [
      {
        name: 'XControl FLEX +',
        image: 'XControl FLEX Plus',
        list: [
          '7 calowy ekran dotykoway',
          'możliwość wyświetlania komunikatów w 34 językach',
          'wbudowane wifi',
          'zdalne programowanie i aktualizacje',
          'w pełni programowalny',
          '20 fabrycznych programów prania spełniających wszystkie podstawowe potrzeby',
          'do 99 programów użytkownika',
        ],
      },
      {
        name: 'XControl +',
        image: 'XControl Plus',
        list: [
          'do 99 programów prania',
          'w pełni programowalny',
          'wyświetlacz graficzny',
          'obsługa w 21 językach, w tym polskim',
          'port USB',
        ],
      },
    ],
    leaflets: [
      { label: 'karta informacyjna', fileName: 'product_overview' },
      {
        label: 'instrukcja instalacji pralnicowirówki',
        fileName: 'FX350_450_600 instalacja',
      },
    ],
  },
];
