export const spare_parts = [
  {
    partID: "1",
    title: "Uszczelka",
    tags: ["pralnice", "pralnicowirówki"],
    image: "spare_part_01",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
  {
    partID: "2",
    title: "Mikrowyłącznik wibracji",
    tags: ["pralnice"],
    image: "spare_part_02",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: true,
    isAllegro: false,
  },
  {
    partID: "3",
    title: "Amortyzator",
    tags: ["pralnice"],
    image: "spare_part_03",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: true,
    isAllegro: false,
  },
  {
    partID: "4",
    title: "Sprężyna zawieszenia",
    tags: ["pralnicowirówki"],
    image: "spare_part_04",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
  {
    partID: "5",
    title: "Uszczelka",
    tags: ["pralnicowirówki"],
    image: "spare_part_05",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
  {
    partID: "6",
    title: "Uszczelka okna",
    tags: ["suszarki"],
    image: "spare_part_06",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: true,
    isAllegro: false,
  },
  {
    partID: "7",
    title: "Zawór spustowy MDB-03RA",
    tags: ["pralnicowirówki"],
    image: "spare_part_07",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: true,
    isAllegro: false,
  },
  {
    partID: "8",
    title: "Plytka mocy sterownika",
    tags: ["pralnicowirówki"],
    image: "spare_part_08",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
  {
    partID: "9",
    title: "Uszczlkea",
    tags: ["pralnice", "pralnicowirówki"],
    image: "spare_part_01",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
  {
    partID: "10",
    title: "Mikrowyłącznik wibracji",
    tags: ["pralnice"],
    image: "spare_part_02",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: true,
    isAllegro: false,
  },
  {
    partID: "11",
    title: "Amortyzator",
    tags: ["pralnicowirówki"],
    image: "spare_part_03",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
  {
    partID: "12",
    title: "Sprężyna zawieszenia",
    tags: ["pralnicowirówki"],
    image: "spare_part_04",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: true,
    isAllegro: false,
  },
  {
    partID: "13",
    title: "Uszczelka",
    tags: ["pralnicowirówki"],
    image: "spare_part_05",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
  {
    partID: "14",
    title: "Uszczelka okna",
    tags: ["pralnicowirówki"],
    image: "spare_part_06",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
  {
    partID: "15",
    title: "Zawór spustowy MDB-03RA",
    tags: ["pralnicowirówki"],
    image: "spare_part_07",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 1920, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
  {
    partID: "16",
    title: "Plytka mocy sterownika",
    tags: ["pralnicowirówki"],
    image: "spare_part_08",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. At culpa asperiores consequatur perspiciatis, placeat blanditiis delectus id illo! Aperiam corrupti dolorum perferendis nemo quia at nulla doloribus libero porro! Adipisci.",
    replacedByPartID: "",
    parameters: [
      { name: "waga", value: 0, unit: "kg" },
      { name: "cena netto", value: 0, unit: "" },
      { name: "kraj pochodzenia", value: "Polska", unit: "" },
      { name: "dostępna", value: "NIE", unit: "" },
    ],
    isBlue: false,
    isAllegro: false,
  },
];
